/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ariel
 */
public class JPanelCliente extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCliente
     */
    public JPanelCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jtf_listar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jbtn_listar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jtf_nombre = new javax.swing.JTextField();
        jPanel32 = new javax.swing.JPanel();
        jlbl_nombre = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jtf_apellido = new javax.swing.JTextField();
        jPanel36 = new javax.swing.JPanel();
        jlbl_apellido = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jcb_tipoDNI = new javax.swing.JComboBox<>();
        jPanel40 = new javax.swing.JPanel();
        jlbl_tipoDNI = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jtf_dni = new javax.swing.JTextField();
        jPanel44 = new javax.swing.JPanel();
        jlbl_dni = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jcb_estadoCivil = new javax.swing.JComboBox<>();
        jPanel48 = new javax.swing.JPanel();
        jlbl_estadoCivil = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jtf_calle = new javax.swing.JTextField();
        jPanel52 = new javax.swing.JPanel();
        jlbl_calle = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jtf_numero = new javax.swing.JTextField();
        jPanel56 = new javax.swing.JPanel();
        jlbl_numero = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        jtf_telefono = new javax.swing.JTextField();
        jPanel60 = new javax.swing.JPanel();
        jlbl_telefono = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        jPanel62 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        jtf_correo = new javax.swing.JTextField();
        jPanel64 = new javax.swing.JPanel();
        jlbl_correo = new javax.swing.JLabel();
        jPanel65 = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jcb_tipoCliente = new javax.swing.JComboBox<>();
        jPanel68 = new javax.swing.JPanel();
        jlbl_tipoCliente = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jbtn_agregar = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jbtn_modificar = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jbtn_eliminar = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jbtn_aceptar = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jbtn_cancelar = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jlbl_mensaje = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 150));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 125));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 125));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setAlignmentX(0.0F);
        jPanel8.setAlignmentY(0.0F);
        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel8.setMinimumSize(new java.awt.Dimension(400, 25));
        jPanel8.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE CLIENTES");
        jPanel8.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setAlignmentX(0.0F);
        jPanel9.setAlignmentY(0.0F);
        jPanel9.setMinimumSize(new java.awt.Dimension(400, 75));
        jPanel9.setPreferredSize(new java.awt.Dimension(400, 75));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setAlignmentX(0.0F);
        jScrollPane1.setAlignmentY(0.0F);

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCliente.setAlignmentX(0.0F);
        jTableCliente.setAlignmentY(0.0F);
        jScrollPane1.setViewportView(jTableCliente);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 0, 204));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 25));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 25));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel14.setAlignmentX(0.0F);
        jPanel14.setAlignmentY(0.0F);
        jPanel14.setMinimumSize(new java.awt.Dimension(50, 25));
        jPanel14.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("DNI");
        jPanel14.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel14, java.awt.BorderLayout.WEST);

        jPanel7.setAlignmentX(0.0F);
        jPanel7.setAlignmentY(0.0F);
        jPanel7.setMinimumSize(new java.awt.Dimension(250, 25));
        jPanel7.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jtf_listar.setAlignmentX(0.0F);
        jtf_listar.setAlignmentY(0.0F);
        jtf_listar.setPreferredSize(new java.awt.Dimension(59, 23));
        jPanel7.add(jtf_listar, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setMinimumSize(new java.awt.Dimension(100, 25));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jbtn_listar.setText("LISTAR");
        jbtn_listar.setAlignmentY(0.0F);
        jbtn_listar.setMaximumSize(new java.awt.Dimension(100, 25));
        jbtn_listar.setMinimumSize(new java.awt.Dimension(100, 25));
        jbtn_listar.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel4.add(jbtn_listar, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setAlignmentX(0.0F);
        jPanel6.setAlignmentY(0.0F);
        jPanel6.setMinimumSize(new java.awt.Dimension(400, 250));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel5.setMinimumSize(new java.awt.Dimension(400, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATOS DEL CLIENTE");
        jLabel2.setAlignmentY(0.0F);
        jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setAlignmentX(0.0F);
        jPanel10.setAlignmentY(0.0F);
        jPanel10.setMinimumSize(new java.awt.Dimension(50, 200));
        jPanel10.setPreferredSize(new java.awt.Dimension(50, 200));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, java.awt.BorderLayout.LINE_START);

        jPanel13.setBackground(new java.awt.Color(255, 153, 153));
        jPanel13.setAlignmentX(0.0F);
        jPanel13.setAlignmentY(0.0F);
        jPanel13.setMinimumSize(new java.awt.Dimension(250, 200));
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel16.setLayout(new java.awt.GridLayout(10, 1, 1, 2));

        jPanel29.setLayout(new java.awt.BorderLayout());

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setAlignmentX(0.0F);
        jPanel30.setAlignmentY(0.0F);
        jPanel30.setMinimumSize(new java.awt.Dimension(90, 25));
        jPanel30.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel30.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("NOMBRE: ");
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setMaximumSize(null);
        jLabel5.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel30.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel30, java.awt.BorderLayout.WEST);

        jPanel31.setBackground(new java.awt.Color(255, 153, 102));
        jPanel31.setAlignmentX(0.0F);
        jPanel31.setAlignmentY(0.0F);
        jPanel31.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanel31.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel31.setLayout(new java.awt.BorderLayout());

        jtf_nombre.setMinimumSize(new java.awt.Dimension(140, 25));
        jtf_nombre.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel31.add(jtf_nombre, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel31, java.awt.BorderLayout.CENTER);

        jPanel32.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel32.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jlbl_nombre.setMaximumSize(new java.awt.Dimension(40, 25));
        jlbl_nombre.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel32.add(jlbl_nombre, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel32, java.awt.BorderLayout.EAST);

        jPanel16.add(jPanel29);

        jPanel33.setLayout(new java.awt.BorderLayout());

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setAlignmentX(0.0F);
        jPanel34.setAlignmentY(0.0F);
        jPanel34.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("APELLIDO: ");
        jLabel7.setAlignmentY(0.0F);
        jLabel7.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel34.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel33.add(jPanel34, java.awt.BorderLayout.WEST);

        jPanel35.setBackground(new java.awt.Color(255, 153, 102));
        jPanel35.setAlignmentX(0.0F);
        jPanel35.setAlignmentY(0.0F);
        jPanel35.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanel35.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel35.setLayout(new java.awt.BorderLayout());

        jtf_apellido.setMinimumSize(new java.awt.Dimension(140, 25));
        jtf_apellido.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel35.add(jtf_apellido, java.awt.BorderLayout.CENTER);

        jPanel33.add(jPanel35, java.awt.BorderLayout.CENTER);

        jPanel36.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel36.setLayout(new java.awt.BorderLayout());

        jlbl_apellido.setMaximumSize(new java.awt.Dimension(40, 25));
        jlbl_apellido.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel36.add(jlbl_apellido, java.awt.BorderLayout.CENTER);

        jPanel33.add(jPanel36, java.awt.BorderLayout.EAST);

        jPanel16.add(jPanel33);

        jPanel37.setLayout(new java.awt.BorderLayout());

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setAlignmentX(0.0F);
        jPanel38.setAlignmentY(0.0F);
        jPanel38.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("TIPO DNI: ");
        jLabel9.setAlignmentY(0.0F);
        jLabel9.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel38.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel37.add(jPanel38, java.awt.BorderLayout.WEST);

        jPanel39.setBackground(new java.awt.Color(255, 153, 102));
        jPanel39.setAlignmentX(0.0F);
        jPanel39.setAlignmentY(0.0F);
        jPanel39.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanel39.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel39.setLayout(new java.awt.BorderLayout());

        jcb_tipoDNI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel39.add(jcb_tipoDNI, java.awt.BorderLayout.CENTER);

        jPanel37.add(jPanel39, java.awt.BorderLayout.CENTER);

        jPanel40.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel40.setLayout(new java.awt.BorderLayout());

        jlbl_tipoDNI.setMaximumSize(new java.awt.Dimension(40, 25));
        jlbl_tipoDNI.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel40.add(jlbl_tipoDNI, java.awt.BorderLayout.CENTER);

        jPanel37.add(jPanel40, java.awt.BorderLayout.EAST);

        jPanel16.add(jPanel37);

        jPanel41.setLayout(new java.awt.BorderLayout());

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setAlignmentX(0.0F);
        jPanel42.setAlignmentY(0.0F);
        jPanel42.setLayout(new java.awt.BorderLayout());

        jLabel11.setText("DNI: ");
        jLabel11.setAlignmentY(0.0F);
        jLabel11.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel42.add(jLabel11, java.awt.BorderLayout.CENTER);

        jPanel41.add(jPanel42, java.awt.BorderLayout.WEST);

        jPanel43.setBackground(new java.awt.Color(255, 153, 102));
        jPanel43.setAlignmentX(0.0F);
        jPanel43.setAlignmentY(0.0F);
        jPanel43.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanel43.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel43.setLayout(new java.awt.BorderLayout());

        jtf_dni.setMinimumSize(new java.awt.Dimension(140, 25));
        jtf_dni.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel43.add(jtf_dni, java.awt.BorderLayout.CENTER);

        jPanel41.add(jPanel43, java.awt.BorderLayout.CENTER);

        jPanel44.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel44.setLayout(new java.awt.BorderLayout());

        jlbl_dni.setMaximumSize(new java.awt.Dimension(40, 25));
        jlbl_dni.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel44.add(jlbl_dni, java.awt.BorderLayout.CENTER);

        jPanel41.add(jPanel44, java.awt.BorderLayout.EAST);

        jPanel16.add(jPanel41);

        jPanel45.setLayout(new java.awt.BorderLayout());

        jPanel46.setBackground(new java.awt.Color(255, 255, 255));
        jPanel46.setAlignmentX(0.0F);
        jPanel46.setAlignmentY(0.0F);
        jPanel46.setLayout(new java.awt.BorderLayout());

        jLabel13.setText("ESTADO CIVIL: ");
        jLabel13.setAlignmentY(0.0F);
        jLabel13.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel13.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel46.add(jLabel13, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel46, java.awt.BorderLayout.WEST);

        jPanel47.setBackground(new java.awt.Color(255, 153, 102));
        jPanel47.setAlignmentX(0.0F);
        jPanel47.setAlignmentY(0.0F);
        jPanel47.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanel47.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel47.setLayout(new java.awt.BorderLayout());

        jcb_estadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel47.add(jcb_estadoCivil, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel47, java.awt.BorderLayout.CENTER);

        jPanel48.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel48.setLayout(new java.awt.BorderLayout());

        jlbl_estadoCivil.setMaximumSize(new java.awt.Dimension(40, 25));
        jlbl_estadoCivil.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel48.add(jlbl_estadoCivil, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel48, java.awt.BorderLayout.EAST);

        jPanel16.add(jPanel45);

        jPanel49.setLayout(new java.awt.BorderLayout());

        jPanel50.setBackground(new java.awt.Color(255, 255, 255));
        jPanel50.setAlignmentX(0.0F);
        jPanel50.setAlignmentY(0.0F);
        jPanel50.setLayout(new java.awt.BorderLayout());

        jLabel15.setText("CALLE: ");
        jLabel15.setAlignmentY(0.0F);
        jLabel15.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel15.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel50.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanel49.add(jPanel50, java.awt.BorderLayout.WEST);

        jPanel51.setBackground(new java.awt.Color(255, 153, 102));
        jPanel51.setAlignmentX(0.0F);
        jPanel51.setAlignmentY(0.0F);
        jPanel51.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanel51.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel51.setLayout(new java.awt.BorderLayout());

        jtf_calle.setMinimumSize(new java.awt.Dimension(140, 25));
        jtf_calle.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel51.add(jtf_calle, java.awt.BorderLayout.CENTER);

        jPanel49.add(jPanel51, java.awt.BorderLayout.CENTER);

        jPanel52.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel52.setLayout(new java.awt.BorderLayout());

        jlbl_calle.setMaximumSize(new java.awt.Dimension(40, 25));
        jlbl_calle.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel52.add(jlbl_calle, java.awt.BorderLayout.CENTER);

        jPanel49.add(jPanel52, java.awt.BorderLayout.EAST);

        jPanel16.add(jPanel49);

        jPanel53.setLayout(new java.awt.BorderLayout());

        jPanel54.setBackground(new java.awt.Color(255, 255, 255));
        jPanel54.setAlignmentX(0.0F);
        jPanel54.setAlignmentY(0.0F);
        jPanel54.setLayout(new java.awt.BorderLayout());

        jLabel17.setText("NÚMERO: ");
        jLabel17.setAlignmentY(0.0F);
        jLabel17.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel17.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel54.add(jLabel17, java.awt.BorderLayout.CENTER);

        jPanel53.add(jPanel54, java.awt.BorderLayout.WEST);

        jPanel55.setBackground(new java.awt.Color(255, 153, 102));
        jPanel55.setAlignmentX(0.0F);
        jPanel55.setAlignmentY(0.0F);
        jPanel55.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanel55.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel55.setLayout(new java.awt.BorderLayout());

        jtf_numero.setMinimumSize(new java.awt.Dimension(140, 25));
        jtf_numero.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel55.add(jtf_numero, java.awt.BorderLayout.CENTER);

        jPanel53.add(jPanel55, java.awt.BorderLayout.CENTER);

        jPanel56.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel56.setLayout(new java.awt.BorderLayout());

        jlbl_numero.setMaximumSize(new java.awt.Dimension(40, 25));
        jlbl_numero.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel56.add(jlbl_numero, java.awt.BorderLayout.CENTER);

        jPanel53.add(jPanel56, java.awt.BorderLayout.EAST);

        jPanel16.add(jPanel53);

        jPanel57.setLayout(new java.awt.BorderLayout());

        jPanel58.setBackground(new java.awt.Color(255, 255, 255));
        jPanel58.setAlignmentX(0.0F);
        jPanel58.setAlignmentY(0.0F);
        jPanel58.setLayout(new java.awt.BorderLayout());

        jLabel19.setText("TELÉFONO: ");
        jLabel19.setAlignmentY(0.0F);
        jLabel19.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel19.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel58.add(jLabel19, java.awt.BorderLayout.CENTER);

        jPanel57.add(jPanel58, java.awt.BorderLayout.WEST);

        jPanel59.setBackground(new java.awt.Color(255, 153, 102));
        jPanel59.setAlignmentX(0.0F);
        jPanel59.setAlignmentY(0.0F);
        jPanel59.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanel59.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel59.setLayout(new java.awt.BorderLayout());

        jtf_telefono.setMinimumSize(new java.awt.Dimension(140, 25));
        jtf_telefono.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel59.add(jtf_telefono, java.awt.BorderLayout.CENTER);

        jPanel57.add(jPanel59, java.awt.BorderLayout.CENTER);

        jPanel60.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel60.setLayout(new java.awt.BorderLayout());

        jlbl_telefono.setMaximumSize(new java.awt.Dimension(40, 25));
        jlbl_telefono.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel60.add(jlbl_telefono, java.awt.BorderLayout.CENTER);

        jPanel57.add(jPanel60, java.awt.BorderLayout.EAST);

        jPanel16.add(jPanel57);

        jPanel61.setLayout(new java.awt.BorderLayout());

        jPanel62.setBackground(new java.awt.Color(255, 255, 255));
        jPanel62.setAlignmentX(0.0F);
        jPanel62.setAlignmentY(0.0F);
        jPanel62.setLayout(new java.awt.BorderLayout());

        jLabel21.setText("E-MAIL");
        jLabel21.setAlignmentY(0.0F);
        jLabel21.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel21.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel62.add(jLabel21, java.awt.BorderLayout.CENTER);

        jPanel61.add(jPanel62, java.awt.BorderLayout.WEST);

        jPanel63.setBackground(new java.awt.Color(255, 153, 102));
        jPanel63.setAlignmentX(0.0F);
        jPanel63.setAlignmentY(0.0F);
        jPanel63.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanel63.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel63.setLayout(new java.awt.BorderLayout());

        jtf_correo.setMinimumSize(new java.awt.Dimension(140, 25));
        jtf_correo.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel63.add(jtf_correo, java.awt.BorderLayout.CENTER);

        jPanel61.add(jPanel63, java.awt.BorderLayout.CENTER);

        jPanel64.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel64.setLayout(new java.awt.BorderLayout());

        jlbl_correo.setMaximumSize(new java.awt.Dimension(40, 25));
        jlbl_correo.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel64.add(jlbl_correo, java.awt.BorderLayout.CENTER);

        jPanel61.add(jPanel64, java.awt.BorderLayout.EAST);

        jPanel16.add(jPanel61);

        jPanel65.setLayout(new java.awt.BorderLayout());

        jPanel66.setBackground(new java.awt.Color(255, 255, 255));
        jPanel66.setAlignmentX(0.0F);
        jPanel66.setAlignmentY(0.0F);
        jPanel66.setLayout(new java.awt.BorderLayout());

        jLabel23.setText("TIPO CLIENTE:");
        jLabel23.setAlignmentY(0.0F);
        jLabel23.setMinimumSize(new java.awt.Dimension(90, 25));
        jLabel23.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel66.add(jLabel23, java.awt.BorderLayout.CENTER);

        jPanel65.add(jPanel66, java.awt.BorderLayout.WEST);

        jPanel67.setBackground(new java.awt.Color(255, 153, 102));
        jPanel67.setAlignmentX(0.0F);
        jPanel67.setAlignmentY(0.0F);
        jPanel67.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanel67.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel67.setLayout(new java.awt.BorderLayout());

        jcb_tipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel67.add(jcb_tipoCliente, java.awt.BorderLayout.CENTER);

        jPanel65.add(jPanel67, java.awt.BorderLayout.CENTER);

        jPanel68.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel68.setLayout(new java.awt.BorderLayout());

        jlbl_tipoCliente.setMaximumSize(new java.awt.Dimension(40, 25));
        jlbl_tipoCliente.setMinimumSize(new java.awt.Dimension(40, 25));
        jPanel68.add(jlbl_tipoCliente, java.awt.BorderLayout.CENTER);

        jPanel65.add(jPanel68, java.awt.BorderLayout.EAST);

        jPanel16.add(jPanel65);

        jPanel13.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel11.setAlignmentX(0.0F);
        jPanel11.setAlignmentY(0.0F);
        jPanel11.setMinimumSize(new java.awt.Dimension(100, 200));
        jPanel11.setLayout(new java.awt.GridLayout(3, 0));

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setAlignmentX(0.0F);
        jPanel15.setAlignmentY(0.0F);
        jPanel15.setLayout(new java.awt.GridLayout(3, 1));

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel18.setAlignmentX(0.0F);
        jPanel18.setAlignmentY(0.0F);
        jPanel18.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel18.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jbtn_agregar.setText("AGREGAR");
        jPanel18.add(jbtn_agregar, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel18);

        jPanel20.setBackground(new java.awt.Color(153, 255, 51));
        jPanel20.setAlignmentX(0.0F);
        jPanel20.setAlignmentY(0.0F);
        jPanel20.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel20.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jbtn_modificar.setText("MODIFICAR");
        jPanel20.add(jbtn_modificar, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel20);

        jPanel21.setBackground(new java.awt.Color(153, 153, 153));
        jPanel21.setAlignmentX(0.0F);
        jPanel21.setAlignmentY(0.0F);
        jPanel21.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel21.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jbtn_eliminar.setText("ELIMINAR");
        jPanel21.add(jbtn_eliminar, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel21);

        jPanel11.add(jPanel15);

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setAlignmentX(0.0F);
        jPanel19.setAlignmentY(0.0F);
        jPanel19.setLayout(new java.awt.GridLayout(3, 1));

        jPanel22.setBackground(new java.awt.Color(204, 204, 204));
        jPanel22.setAlignmentX(0.0F);
        jPanel22.setAlignmentY(0.0F);
        jPanel22.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel22.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel22.setLayout(new java.awt.BorderLayout());
        jPanel19.add(jPanel22);

        jPanel23.setBackground(new java.awt.Color(153, 255, 51));
        jPanel23.setAlignmentX(0.0F);
        jPanel23.setAlignmentY(0.0F);
        jPanel23.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel23.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jbtn_aceptar.setText("ACEPTAR");
        jPanel23.add(jbtn_aceptar, java.awt.BorderLayout.CENTER);

        jPanel19.add(jPanel23);

        jPanel24.setBackground(new java.awt.Color(153, 153, 153));
        jPanel24.setAlignmentX(0.0F);
        jPanel24.setAlignmentY(0.0F);
        jPanel24.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel24.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel24.setLayout(new java.awt.BorderLayout());

        jbtn_cancelar.setText("CANCELAR");
        jPanel24.add(jbtn_cancelar, java.awt.BorderLayout.CENTER);

        jPanel19.add(jPanel24);

        jPanel11.add(jPanel19);

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setAlignmentX(0.0F);
        jPanel17.setAlignmentY(0.0F);
        jPanel17.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel17.setPreferredSize(new java.awt.Dimension(100, 60));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel17);

        jPanel6.add(jPanel11, java.awt.BorderLayout.LINE_END);

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setAlignmentX(0.0F);
        jPanel12.setAlignmentY(0.0F);
        jPanel12.setMinimumSize(new java.awt.Dimension(400, 25));
        jPanel12.setPreferredSize(new java.awt.Dimension(400, 25));

        jlbl_mensaje.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbl_mensaje.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_mensaje.setAlignmentY(0.0F);
        jlbl_mensaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel12.add(jlbl_mensaje);

        jPanel6.add(jPanel12, java.awt.BorderLayout.PAGE_END);

        add(jPanel6, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JButton jbtn_agregar;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_listar;
    private javax.swing.JButton jbtn_modificar;
    private javax.swing.JComboBox<String> jcb_estadoCivil;
    private javax.swing.JComboBox<String> jcb_tipoCliente;
    private javax.swing.JComboBox<String> jcb_tipoDNI;
    private javax.swing.JLabel jlbl_apellido;
    private javax.swing.JLabel jlbl_calle;
    private javax.swing.JLabel jlbl_correo;
    private javax.swing.JLabel jlbl_dni;
    private javax.swing.JLabel jlbl_estadoCivil;
    private javax.swing.JLabel jlbl_mensaje;
    private javax.swing.JLabel jlbl_nombre;
    private javax.swing.JLabel jlbl_numero;
    private javax.swing.JLabel jlbl_telefono;
    private javax.swing.JLabel jlbl_tipoCliente;
    private javax.swing.JLabel jlbl_tipoDNI;
    private javax.swing.JTextField jtf_apellido;
    private javax.swing.JTextField jtf_calle;
    private javax.swing.JTextField jtf_correo;
    private javax.swing.JTextField jtf_dni;
    private javax.swing.JTextField jtf_listar;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_numero;
    private javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getjTableCliente() {
        return jTableCliente;
    }

    public javax.swing.JButton getJbtn_aceptar() {
        return jbtn_aceptar;
    }

    public javax.swing.JButton getJbtn_agregar() {
        return jbtn_agregar;
    }

    public javax.swing.JButton getJbtn_cancelar() {
        return jbtn_cancelar;
    }

    public javax.swing.JButton getJbtn_eliminar() {
        return jbtn_eliminar;
    }

    public javax.swing.JButton getJbtn_listar() {
        return jbtn_listar;
    }

    public javax.swing.JButton getJbtn_modificar() {
        return jbtn_modificar;
    }

    public javax.swing.JComboBox<String> getJcb_estadoCivil() {
        return jcb_estadoCivil;
    }

    public javax.swing.JComboBox<String> getJcb_tipoCliente() {
        return jcb_tipoCliente;
    }

    public javax.swing.JComboBox<String> getJcb_tipoDNI() {
        return jcb_tipoDNI;
    }

    public javax.swing.JLabel getJlbl_apellido() {
        return jlbl_apellido;
    }

    public javax.swing.JLabel getJlbl_calle() {
        return jlbl_calle;
    }

    public javax.swing.JLabel getJlbl_correo() {
        return jlbl_correo;
    }

    public javax.swing.JLabel getJlbl_dni() {
        return jlbl_dni;
    }

    public javax.swing.JLabel getJlbl_estadoCivil() {
        return jlbl_estadoCivil;
    }

    public javax.swing.JLabel getJlbl_mensaje() {
        return jlbl_mensaje;
    }

    public javax.swing.JLabel getJlbl_nombre() {
        return jlbl_nombre;
    }

    public javax.swing.JLabel getJlbl_numero() {
        return jlbl_numero;
    }

    public javax.swing.JLabel getJlbl_telefono() {
        return jlbl_telefono;
    }

    public javax.swing.JLabel getJlbl_tipoCliente() {
        return jlbl_tipoCliente;
    }

    public javax.swing.JLabel getJlbl_tipoDNI() {
        return jlbl_tipoDNI;
    }

    public javax.swing.JTextField getJtf_apellido() {
        return jtf_apellido;
    }

    public javax.swing.JTextField getJtf_calle() {
        return jtf_calle;
    }

    public javax.swing.JTextField getJtf_correo() {
        return jtf_correo;
    }

    public javax.swing.JTextField getJtf_dni() {
        return jtf_dni;
    }

    public javax.swing.JTextField getJtf_nombre() {
        return jtf_nombre;
    }

    public javax.swing.JTextField getJtf_numero() {
        return jtf_numero;
    }

    public javax.swing.JTextField getJtf_telefono() {
        return jtf_telefono;
    }

    public javax.swing.JTextField getJtf_listar() {
        return jtf_listar;
    }

    
    
}
